### ISSUE TITLE
CharServer: Character creation fails due not implemented packages

### ISSUE THREAD

**Issue by Ebbo** [adrianopteodoro/dboserver#1]
Hello,

the character creation is not working right now. The client shows the message:
"Char already exists."
The packages are send correctly from the client but the server receives an not yet implemented package. 
This can be workaround by entering the char manually into the database.

A solution would be to add the 2-3 missing packages into classes with correct resulting opcodes.

**Comment by adrianopteodoro** [comment]
In progress :)
